
<head>
   <meta charset="utf-8">  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">
  <script  src="https://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="  crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    </head>
  <div class="row">
    <div class="pull-left">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="regis" class="btn btn-success" role="button">ADD</a>
    </div>
    <!-- <div class="container container-form">
      <div class="panel panel-primary">
        <div class="panel-body">

                <table data-toggle="table" id="example" class="table table-dark table-striped" data-url="public/php/selectJson.php">


                    <thead>
                        <tr>
                            <th data-field="id"> ลำดับ </th>
                            <th data-field="event_name"> ชื่อกิจกรรม</th>
                            <th data-field="event_date"> เวลา</th>
                        </tr> 
                    </thead>

                </table>        
        </div>
      </div>
    </div> 
     -->
    <?php
require_once 'config.php';
    //  echo $this->assets->outputCss('styleslogin');       
    // echo $this->assets->outputJs('scripts'); 
try{     
  
    $sql = "select id,event_name,event_date,event_detail,event_picture from event";
    if(isset($_POST['event_name'])){
  $event_name=$_POST['event_name'];
  $event_date=$_POST['event_date'];
        $sql.="  where event_name=:event_name";
        $sql.="  where event_date=:event_date";
  }
    $stmt = $pdo->prepare($sql);
    $stmt->bindParam(':event_name', $event_name, PDO::PARAM_STR);
    $stmt->bindParam(':event_date', $event_date, PDO::PARAM_STR);
    $stmt->execute();
    $n=1;
    $n="table table-dark table-striped";
    $n1="table";
    echo "<thead>";
    echo "<table class=".$n."data-toggle".$n1.">";
    echo "<tr>";
    echo "<th> ลำดับ </th>";
    echo "<th> ชื่อกิจกรรม </th>";
    echo "<th> เวลา </th>";
    echo "<th></th>";
    echo "<th></th>";
    echo "</tr>";
    echo "</thead>";  
    if($stmt->rowCount() > 0){
        while($row = $stmt->fetch()){
    
        echo "<tr><th>" . $row['id'] . "</th><th>" . $row['event_name'] . "</th><th>". $row['event_date'] . "</th>"; 
        ?>
<!--         echo "<dir class="."row>";
        echo "<form "."action=".""." method="."post>";
        echo "<input type="."hidden"." name="."nub"." id="."nub"." value=". $n." class="."form-control>";
        echo "<div class="."form-group>";
        echo "<th>";
        echo "<a href="."edit"." name="."edit"." value=".$n." id="."edit"."class="."btn btn-success"." role="."button".">Edit</a>";
        echo "</th>";
        echo "</div>";
        echo "<div class="."form-group>";
        echo "<th>";
        echo "<a href="."delete"." name="."delete"." value=".$n." id="."delete"." class="."btn btn-success"." role="."button".">Delete</a>";
        echo "</th>";
        echo "</div>";
        echo "</form>";
        echo "</dir>";
        echo "<tr>";  -->
        <dir class="row">
        <form action="Edit" method="post">
        <input type="hidden" name="nub2" id="nub2" value="3" class="form-control">
        <div class="form-group">
        <th>
        <a type="submit" href="edit?id=<?php echo $row['id'] ?>" name="edit" value="{&n}" id="edit" class="btn btn-success" role="button">Edit</a>
        </th>
        </div>
        <div class="form-group">
        <th>
        <a type="submit" href="delete?id=<?php echo $row['id'] ?>" name="delete" value="{&n}" id="delete" class="btn btn-success" role="button">Delete</a>
        </th>
        </div>
        </form>
        </dir>
        <tr>
        <?php
        } 
    echo "</table>";
        unset($stmt);
    } else{
    echo " No records matching your query were found.";

    }
    
} catch(PDOException $e){
    die("ERROR: Could not prepare/execute query: $sql. " . $e->getMessage());
}
?>

